#!/bin/sh

if [ "$ACTION" = "pressed" -a "$BUTTON" = "wps" -a (! -f /tmp/wpsbuttonlock) ]; then
set -C; > /tmp/wpsbuttonlock	#1 wps instance only
	(
	WPSLED="/sys/class/leds/wndr4700:white:logo/brightness"
	for i in $(seq 0 59); 
	do
		sleep 1
		echo 1 > $WPSLED
		sleep 1
		echo 0 > $WPSLED
	done
	) &
	WPSLEDPID=$!

ffactiviy_check(){
	set -C; > /tmp/wpsledlock_by_$1
	if [ "$status_$1"=="FAIL" ]; then
		( rm -f /tmp/wpsledlock_by_$1; return; )
	else
		for i in $(seq 0 23); do
			if [ `hostapd_cli -p /var/run/hostapd -i $1 wps_get_status | grep "PBC Status" | cut -d' ' -f3` = "Active" ] ; 
			then 
				sleep 5; 
				wait;
			else 
				( rm -f /tmp/wpsledlock_by_$1; return; )
			fi
		done
	fi
	
	return 0;	#its goog to return
}

	cd /var/run/hostapd
	for socket in *; do
		[ -S "$socket" ] || continue
		status_$socket=$(hostapd_cli -i "$socket" wps_pbc)
		ffactiviy_check "$socket" &&		
	done

	while [ -f /tmp/wpsledlock_by_* ]
	do
		sleep 3
	done
	wait

	kill $WPSLEDPID
	
	rm -f /tmp/wpsledlock_by_*
	rm /tmp/wpsbuttonlock
	echo 0 > $WPSLED
fi
return 0
